export enum tagTypes {
  buyer = 'buyer',
  seller = 'seller',
  user = 'user',
  profile = 'profile',
  category = 'category',
  auth = 'auth',
  CheckInOut = 'CheckInOut',
  Employee = 'Employee',
  Projects = 'Projects',
  TaskManagement = 'TaskManagement',
  Leaves = 'Leaves',
  LoginHistory = 'LoginHistory',
  Friendship = 'Friendship',
  ChatMessages = 'ChatMessages',
  admin = 'admin',
}

export const tagTypesList = [
  tagTypes.buyer,
  tagTypes.seller,
  tagTypes.user,
  tagTypes.category,
  tagTypes.profile,
  tagTypes.Projects,
  tagTypes.Employee,
  tagTypes.TaskManagement,
  tagTypes.Leaves,
  tagTypes.LoginHistory,
  tagTypes.auth,
  tagTypes.Friendship,
  tagTypes.ChatMessages,
  tagTypes.admin,
];
